kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-gitlab
  namespace: gitlab
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "rook-ceph-block"
  resources:
    requests:
      storage: 20Gi
